type Snack {
  id: ID!
  name: String!
  description: String!
  price: Float!
  new: Boolean
  store: Store!
  comments: [SnackComment!]!
  createdAt: String!
  updateAt: String!
}

type SnackComment {
  id: ID!
  comment: String!
  user: User!
  snack: Snack!
  createdAt: String!
  updateAt: String!
}

type Query {
  snacks: [Snack!]!
  snack(id: ID!): Snack
}

type Mutation {
  createSnack(
    name: String!
    description: String!
    price: Float!
    new: Boolean
    store_id: ID!
  ): Snack
  createSnackComment(
    snack_id: ID!
    user_id: ID!
    comment: String!
  ): SnackComment
}
