type Order {
  id: ID!
  client: User!
  store: Store!
  note: String
  value: Float
  status: Status!
  items: [OrderItem!]!
  createdAt: String!
  updatedAt: String!
}
# Verify most
enum Status {
  PENDING
  TRANSPORT
  FINISHED
  CANCELED
}

type OrderItem {
  id: ID!
  amount: Int!
  value: Float!
  snack: Snack!
  order: Order!
  createdAt: String!
  updatedAt: String!
}

type Query {
  orders: [Order!]!
  order(id: ID!): Order
}

input ItemInput {
  amount: Int!
  value: Float!
  snack_id: ID!
}

type Mutation {
  createOrder(
    client_id: ID!
    store_id: ID!
    note: String
    status: String
    items: [ItemInput!]!
  ): Order
}
