type Store {
  id: ID!
  name: String!
  description: String!
  phone: String!
  freeDelivery: Float!
  owner: User!
  address: Address!
  available: Boolean!
  snacks: [Snack!]!
  classifications: [StoreClassification!]!
  createdAt: String!
  updatedAt: String!
}

type StoreClassification {
  id: ID!
  classification: Float!
  user: User!
  store: Store!
  createdAt: String!
  updatedAt: String!
}

type Query {
  stores: [Store!]!
  store(id: ID!): Store!
  searchStore(key: String!): [Store!]!
}

type Mutation {
  createStore(
    name: String!
    description: String!
    phone: String!
    freeDelivery: Float!
    owner_id: ID!
    address: AddressInput!
    available: Boolean
  ): Store
  createStoreClassification(
    store_id: ID!
    user_id: ID!
    classification: Float!
  ): StoreClassification
}
