type User {
  id: ID!
  name: String!
  phone: String!
  username: String!
  password: String!
  lastAccess: String
  autoPayment: Boolean
  address: Address!
  createdAt: String!
  updatedAt: String!
}

type Query {
  users: [User!]!
  user(id: ID!): User
}

type Mutation {
  createUser(
    name: String!
    phone: String!
    username: String!
    password: String!
    autoPayment: Boolean
    address: AddressInput!
  ): User!
}
